---
- name: install ntp
  apt:
    name: ntp
    state: present

- name: install openssl
  apt: 
    name: openssl
    state: present
- name: install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: Setup docker http Proxy systemd directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode:  0755
- name: Create docker http_proxy service file
  template: src=http-proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/http-proxy.conf
  notify: restart docker

- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: install kubelet
  apt:
    name: kubelet
    state: present
    update_cache: true

- name: install kubeadm
  apt:
    name: kubeadm
    state: present

- name: install kubectl
  apt:
    name: kubectl
    state: present

- name: Install git
  apt:
    name: git
    state: present
